theme :minima 
title:   Real Vybz 
author: Kingman 
email: king@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
 welcome to real vybz enjoy a taste of jamica and what it has to offer 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
